name: "Hello world docker action"
description: "Our first training docker action"
inputs:
  who-to-greet:
    description: "Who to greet"
    required: true
    default: "epo"
outputs:
  time:
    description: "The time we said hello"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.who-to-greet }}
