name: Docker Action

on: [workflow_dispatch]

jobs:
  docker-action:
    name:  Running Docker Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.0
        
      - name: Run Docker Action
        uses: ./.github/actions/hello-world-docker-action
        id: hello-id
        with:
          who-to-greet: super-linters
      - name: Print Outputs
        run: echo "The time was ${{ steps.hello-id.outputs.time }}"
        
      - run: echo "### Something :rocket:" >> $GITHUB_STEP_SUMMARY
